-- MySQL Script generated by MySQL Workbench
-- Dom 13 Mai 2018 23:51:24 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SGD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SGD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SGD` DEFAULT CHARACTER SET utf8 ;
USE `SGD` ;

-- -----------------------------------------------------
-- Table `SGD`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGD`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` BIGINT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGD`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGD`.`cidade` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCidade`),
  UNIQUE INDEX `idCidade_UNIQUE` (`idCidade` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGD`.`bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGD`.`bairro` (
  `idBairro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cidade_idCidade` INT NOT NULL,
  PRIMARY KEY (`idBairro`),
  INDEX `fk_bairro_cidade1_idx` (`cidade_idCidade` ASC),
  UNIQUE INDEX `idBairro_UNIQUE` (`idBairro` ASC),
  CONSTRAINT `fk_bairro_cidade1`
    FOREIGN KEY (`cidade_idCidade`)
    REFERENCES `SGD`.`cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGD`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGD`.`endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro_idBairro` INT NOT NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_endereco_bairro1_idx` (`bairro_idBairro` ASC),
  UNIQUE INDEX `idEndereco_UNIQUE` (`idEndereco` ASC),
  CONSTRAINT `fk_endereco_bairro1`
    FOREIGN KEY (`bairro_idBairro`)
    REFERENCES `SGD`.`bairro` (`idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGD`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGD`.`entrega` (
  `idEntrega` INT NOT NULL AUTO_INCREMENT,
  `entregador` VARCHAR(45) NULL,
  `observacoes` VARCHAR(45) NULL,
  `status` VARCHAR(10) NOT NULL,
  `criacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizacao` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`idEntrega`),
  INDEX `fk_entrega_endereco1_idx` (`endereco_idEndereco` ASC),
  UNIQUE INDEX `idEntrega_UNIQUE` (`idEntrega` ASC),
  CONSTRAINT `fk_entrega_endereco1`
    FOREIGN KEY (`endereco_idEndereco`)
    REFERENCES `SGD`.`endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGD`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGD`.`pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `valor` INT NOT NULL,
  `formaPagamento` VARCHAR(10) NOT NULL,
  `observacoes` VARCHAR(45) NULL,
  `status` VARCHAR(10) NOT NULL,
  `criacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizacao` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `cliente_idCliente` INT NOT NULL,
  `entrega_idEntrega` INT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_pedido_cliente1_idx` (`cliente_idCliente` ASC),
  INDEX `fk_pedido_entrega1_idx` (`entrega_idEntrega` ASC),
  UNIQUE INDEX `idPedido_UNIQUE` (`idPedido` ASC),
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `SGD`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_entrega1`
    FOREIGN KEY (`entrega_idEntrega`)
    REFERENCES `SGD`.`entrega` (`idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGD`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGD`.`produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` INT NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `quantidade` INT NOT NULL DEFAULT 0,
  `imagem` VARCHAR(100) NULL,
  PRIMARY KEY (`idProduto`),
  UNIQUE INDEX `idProduto_UNIQUE` (`idProduto` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGD`.`pedido_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGD`.`pedido_produto` (
  `quantidade` TINYINT(2) NOT NULL DEFAULT 0,
  `pedido_idPedido` INT NOT NULL,
  `produto_idProduto` INT NOT NULL,
  INDEX `fk_pedido_produto_pedido1_idx` (`pedido_idPedido` ASC),
  INDEX `fk_pedido_produto_produto1_idx` (`produto_idProduto` ASC),
  PRIMARY KEY (`pedido_idPedido`, `produto_idProduto`),
  CONSTRAINT `fk_pedido_produto_pedido1`
    FOREIGN KEY (`pedido_idPedido`)
    REFERENCES `SGD`.`pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_produto_produto1`
    FOREIGN KEY (`produto_idProduto`)
    REFERENCES `SGD`.`produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGD`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGD`.`administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;

CREATE USER 'UserSGD' IDENTIFIED BY 'gestaoeficiente';

GRANT SELECT, INSERT, TRIGGER ON TABLE `SGD`.* TO 'UserSGD';
GRANT SELECT ON TABLE `SGD`.* TO 'UserSGD';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ----------------------------------------------------
-- INSERTS
-- ----------------------------------------------------

INSERT INTO cidade (idCidade, nome) VALUES
(1, 'Belo Horizonte');

INSERT INTO bairro (idBairro, nome, cidade_idCidade) VALUES
(1, 'Hospitais', 1),
(2, 'Centro', 1);

INSERT INTO administrador (idAdministrador, email, senha) VALUES
(1, 'admin@admin', '21232f297a57a5a743894a0e4a801fc3');
